version: '3'
services:
    nginx:
        image: nginx:1.10
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8002:80"
        depends_on:
            - php
    php:
        build:
            context: ./docker
            dockerfile: php.docker
        volumes:
            - ./:/var/www
        depends_on:
            - db
    db:
        image: mysql:8.0
        volumes:
            - ./storage/docker/mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=db_password"
            - "MYSQL_USER=db_user"
            - "MYSQL_PASSWORD=db_password"
            - "MYSQL_DATABASE=db_name"
        ports:
            - 33061:3306
