version: '3'
services:
    nginx:
        image: nginx:1.10
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8001:80"
        depends_on:
            - php
    php:
        build:
            context: ./docker
            dockerfile: php.docker
        volumes:
            - ./:/var/www
        depends_on:
            - db
    db:
        image: postgres:10.6
        volumes:
            - ./var/docker/postgresql:/var/lib/postgresql/data
            - ./docker/db/dump:/var/www
        working_dir: /var/www
        environment:
            - "POSTGRES_USER=db_user"
            - "POSTGRES_PASSWORD=db_password"
            - "POSTGRES_DB=db_name"
        ports:
            - 5433:5432
